### PR TITLE
Improve error display

### PR DESCRIPTION
**Pull request by danielfdsilva**
Contribute to https://github.com/NASA-IMPACT/nasa-apt/issues/470

From the issue's AC:
1) Error toasts will stick around until the user dismisses them
2) On the fatal error page, there's a message asking the user to refresh. This was also added to other static error messages. The toast alerts are a result of a user action and they can retry the action immediately without having to refresh.
3) The server response is already being included in the message. Sometimes you'll get something like "Network Error" when the server is unreachable (the gcc problems for example). There no more info to show. To the fatal error page I added the error details which may help debugging.

The fatal error page can be tested by triggering an error. For example add `throw new Error('Test dev error');` in the `app/assets/scripts/components/home/index.js L@222`

### CODE REVIEW

**Review by oliverroick — COMMENTED** [review]
The changes look good, but the the error details are a bit useless because they reference bundled code. Any plans to include source maps for production builds?

**Comment by danielfdsilva** [comment]
@oliverroick To have source maps in the production build we'd need to change how the build system works on APT - the setup is somewhat old.
However, without a error tracking service (https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/353) they would not be very useful. The error stack would still show the bundled paths, only when opening the console would the devtools use the source maps. The details may provide some insight into what is happening, in case a user just screenshots the page and sends the error our way.
Any idea on how to approach this differently?

**Comment by danielfdsilva** [comment]
@oliverroick To have source maps in the production build we'd need to change how the build system works on APT - the setup is somewhat old.
However, without a error tracking service (https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/353) they would not be very useful. The error stack would still show the bundled paths, only when opening the console would the devtools use the source maps. The details may provide some insight into what is happening, in case a user just screenshots the page and sends the error our way.
Any idea on how to approach this differently?

**Comment by oliverroick** [comment]
> To have source maps in the production build we'd need to change how the build system works on APT - the setup is somewhat old.

How come the setup is "somewhat old"? Wasn't the project changed to the current build system just over a year ago? Frankly, this begs the question why we're using a build system that can't even produce something as fundamental as source maps.

How much of a lift is it to enable source maps? I think, we should do this the proper way and enable source maps, because they are also critical for error tracking in Sentry. Without knowing where an exception was raised, you'll always find yourself in the dark when you try to track down an issue. Bundled stack traces are just not useful, you might be able to identify where the error was raised but the error's source is often deeper in the call stack and you'll have a hard time trying to find that source without a proper stack trace. 

So, contrary to what you said in #353, source maps are critical for success. Without them you'll only ever know that something has happened but not what and why it happened.

**Comment by danielfdsilva** [comment]
You raise very good points and I have to take a step back and agree with you here.
Sourcemaps are indeed critical and without them we're likely to understand very little.

You're also correct that the current build system was implemented a little over a year ago, however this was not the "brand new thing", but the version of project-seed that was at hand. Since then we looked into the limitations of project-seed and moved to a solution which uses parcel as a base (a much more stable tool).

The project-seed version that APT uses, still leverages browserify as the bundler and a series of other plugins for other parts of the process (minification, file revision, etc). Because of this split, during the production build, sourcemaps are not properly created.

I'll have a look to see what our options are and report back.

**Comment by danielfdsilva** [comment]
@oliverroick Looking a bit more into this, it does not seem straightforward to just add source maps to production. With some research it could probably be done, but we'd still have an old system.

I think we'd be better off with trying to update the build system to the project-seed parcel alternative, which should not be very time consuming. I can have a deeper look, but before moving too much into this, I'd like your thoughts on the approach.

**Review by oliverroick — COMMENTED** [review]
The new build looks ok. The error details are still shown with the bundled source. Should we look into something like [StackTrace.js](https://www.stacktracejs.com) to produce more meaningful stack traces?

**Comment by danielfdsilva** [comment]
This is very interesting. Will give it a look.

**Comment by oliverroick** [comment]
Oh ok, that's a lot! The only way we can reduce would be to introduce code splitting. What's the planning in terms of error logging? Do you think we can use source maps to unbundle stack trace information?

Going to to approve this PR, it seems it's a big lift to make this work just for the error page and it doesn't seem to be worth the effort.

**Review by oliverroick — APPROVED** [review]

**Comment by danielfdsilva** [comment]
@oliverroick Looking at the comment on the other PR, it seems we're [skipping error logging/tracking](https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/353#issuecomment-1083294405) at least if it means using a 3rd party service.

**Pull request merged**
