### PR TITLE
Add table of contents

### PR DESCRIPTION
**Pull request by frozenhelium**
Related to: https://github.com/NASA-IMPACT/nasa-apt/issues/642

Let's also make sure heading actions (i.e. Show comments) are visible in view mode (i.e. only hidden in pdf-preview mode)

### CODE REVIEW

**Review by sunu — CHANGES_REQUESTED** [review]
@frozenhelium This looks great! The only thing that found odd is that `Show comments` shows up in the table of contents entries. May be we should remove those bits before generating the table of content entries.
image

**Review by wrynearson — COMMENTED** [review]
Hey @frozenhelium, looking good!

I tested this in `pdf-preview` mode (and didn't see any of these changes in the download section. I want to confirm that that's the expected behavior at this time.

Regarding the Table of Contents, in addition to @sunu's highlight of "show comments" being present, future work re: page breaks should be done – for this test PDF, there's a full blank page between the `ToC` and the `title`:

image

Tagging @sunu that the `Introduction` section has a large page break as well:
image

Everything else looks good. I think if @frozenhelium can remove the "Show comments" line quickly, we can then merge this into staging.

**Review by wrynearson — APPROVED** [review]
LGTM!

image

**Comment by wrynearson** [comment]
I'm going to merge this so that the APT team can test this. cc @sunu @frozenhelium

**Review by sunu — APPROVED** [review]

**Pull request merged**
