### PR TITLE
Fix/journal styling

### PR DESCRIPTION
**Pull request by kamicut**
Checklist from @bwbaker1's [feedback](https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/421#issuecomment-1721664723). [doc](https://docs.google.com/document/d/1wKToz87CcWgAWU3MIsMBz6BzVjTWzSz59hObetZItzg/edit) for more details and screenshots.

- [x] Centered title
- [x] Unique affiliations should be listed with superscripts
- [x] Duplicate affiliations should not be listed
- [x] Corresponding author name/email should be listed right below the affiliations and above the keypoints.
- [x] `Key Points` should be bulleted (previously, a carriage return automatically adds a bullet point)
- [x] Remove document information (`Version`, `Release date`, and `DOI`)
- [x] Page break after `Key Points`
- [x] Keywords have double colons (::). One of these needs to be removed. 
- [ ] Algorithm Usage Constraints should be section 4, not section 9
- [ ] Fix remaining heading numbering (see doc, point 9)

### CODE REVIEW

**Comment by kamicut** [comment]
This is what the affiliations look like now in the draft PR: 

Screenshot 2023-09-28 at 6 19 32 PM

**Review by wrynearson — COMMENTED** [review]
Everything you checked off looks good @kamicut!

One issue I found is with multi-level lists – they only have the content, and not the list itself. Do you have any idea why that is?

image

image

**Comment by wrynearson** [comment]
☝️ works locally and on staging for `document` pdfs but not for `journal` PDFs

**Review by wrynearson — APPROVED** [review]
Thanks @kamicut! LGTM

**Pull request merged**
