### PR TITLE
indent paragraphs in document pdf

### PR DESCRIPTION
**Pull request by kamicut**
Indents paragraphs in document PDFs to match journal style (24pt indent)

https://github.com/NASA-IMPACT/nasa-apt/issues/620

### CODE REVIEW

**Review by wrynearson — CHANGES_REQUESTED** [review]
@kamicut I found a few unintended changes from this PR. None of these are very important, but should be addressed if they're simple fixes. If they're more complex, we can discuss how to prioritize them:

1. Spacing between in-line citations increases.
    - Old:
        image
    - New:
        image
2. The spacing of lists (ordered and unordered) between the bullet/number and the text is increased.
    - Old:
        image
    - New:
        image
3. Test is indented within tables.
    - Old:
        image
    - New:       
        image
4. The user-submitted names in sections 6.3-6.4 are indented, but shouldn't be.
    - Old:
        image
    - New:
        image

**Comment by batpad** [comment]
Thanks for the catches and thorough testing @wrynearson !

@kamicut am guessing this might be a bit of CSS foolery, but all reasonably easily doable?

**Comment by wrynearson** [comment]
We're going to deprioritize this for now until we move forward with the Journal PDF implementation

**Comment by frozenhelium** [comment]
Closing in favor of https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/429

**Pull request closed without merging**
