### PR TITLE
Support DOI field when importing references from bibtex

### PR DESCRIPTION
**Pull request by danielfdsilva**
The api to get the values from the bibtex was not properly implemented and the DOI field was being excluded.
This PR changes the import format and api fixing the problem

### CODE REVIEW

**Comment by aboydnw** [comment]
@danielfdsilva I am hearing that @bwbaker1 found some other fields that aren't importing correctly. Brad, do you have a document that outlines other fields?

**Review by naomatheus — COMMENTED** [review]
Hey @danielfdsilva.

There is a comment in `comment-center.js` about a dependency that is no longer supported.
Could you take a look and let me know if this needs an update before merging?

**Comment by danielfdsilva** [comment]
@naomatheus No need to worry about it, but I fixed it for completeness

**Review by naomatheus — APPROVED** [review]
Comment center dependency was updated.

**Pull request merged**
