### PR TITLE
Add Cypress

### PR DESCRIPTION
**Pull request by oliverroick**
Preparing for future work where we need to add tests, also we should build a habit of writing tests for the features we build. 

This PR sets up Cypress and adds one simple test.

### CODE REVIEW

**Comment by naomatheus** [comment]
Confirmed and working.

**Review by naomatheus — COMMENTED** [review]
Confirmed and working

**Review by naomatheus — APPROVED** [review]
Approved.

**Review by naomatheus — APPROVED** [review]

**Comment by oliverroick** [comment]
@naomatheus How have you approved this? It's strange, I see your approval but it looks different than in other PRs and I can't merge without bypassing branch protections

**Pull request merged**
