### PR TITLE
Error tracking

### PR DESCRIPTION
**Pull request by danielfdsilva**
Branched from https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/352

I've been exploring error tracking and logging applications that remotely store errors details so we can more easily trace an error when it is reported.
I've looked at:
- [Sentry](https://sentry.io)
- [Data Dog](https://www.datadoghq.com/)
- [Log Rocket](https://logrocket.com/)

I didn't do an extensive analysis of all options, but I settled on Sentry since it is the one that seemed simpler to use and more dedicated to the error logging. The other options seemed more full service analytics.

This PR sets up Sentry logging, capturing uncaught errors and errors caught by React's error boundary (The screen with the satellite circling the planet.)  
Besides logging the stack trace it also logs some actions the user took like for example the items click (It does this referring to the DOM node path).

Because of the way the bundler builds the site it is not possible to use sourcemaps in the production environment, however I don't think that is critical for success. If this logging system ends up being useful we may consider a more detailed implementation with the inclusion of sourcemaps.

**Issues page:**
Screen Shot 2022-03-28 at 18 27 23

**Single issue:**
Screenshot 2022-03-28 at 18-28-07 Error fatal reviews! - developmentseed - apt

---

I just realized that the free plan only offers 1 seat, so I can't give anyone access to this project. If we look at the paid alternative there are unlimited members.  
Is this a deal breaker? @leothomas @aboydnw @oliverroick

### CODE REVIEW

**Comment by aboydnw** [comment]
how much are the paid plans? is this something we could see ourselves using on other projects?

**Comment by danielfdsilva** [comment]
The "Team Plan" starts with 26$ month for unlimited user. They limit based on data. https://sentry.io/pricing/
There could definitely be other projects benefiting from this, first that comes to mind is SNWG.
@aboydnw

**Comment by aboydnw** [comment]
Maybe VEDA as well @danielfdsilva ?
and is this something that you would envision us using in the short term to locate errors, or something that NASA would want to support operationally for error messaging going forward on APT?

**Comment by danielfdsilva** [comment]
From what I understood Sentry even has a "bug report form" that may be displayed when the app crashes to gather additional feedback. This feedback will then be connected to the reported error. Sentry can also connect to issue trackers and source repos to further inform the errors.

NASA already has its own feedback form, but looking into a more cohesive approach could be interesting.

**Comment by aboydnw** [comment]
So I asked Ashish about this during the checkin call today. He said we might run into issues when migrating to NGAP later this year. He asked if there is something similar in AWS that we could use, then that might be a better approach. Otherwise, he and Aaron were on board with not implementing this and only address ACs 1&2 from https://github.com/NASA-IMPACT/nasa-apt/issues/470

**Comment by wrynearson** [comment]
@sunu is this something that you think would be good to pick up / restart for APT?

**Comment by sunu** [comment]
@wrynearson as Anthony mentioned above, the client will probably not want to ship error contexts out to a third party service like Sentry. In that case, we need to check if AWS provides an alternative.

**Comment by wrynearson** [comment]
Ah sorry @sunu, I didn't read this PR carefully – I was just referring to "Error tracking" in general. I'll close it for now.

**Pull request closed without merging**
