### PR TITLE
sort contacts for journal pdf and remove reviewers

### PR DESCRIPTION
**Pull request by kamicut**
- Sorts the contacts in the Journal PDF in the author headline
- Removes authors that have the "Document Reviewer" role from the authors list and corresponding authors list

### CODE REVIEW

**Comment by kamicut** [comment]
@wrynearson in `wills-test-atbd` I created 3 contacts: Will Rynearson (Corresponding Author and Document Reviewer), Corresponding Author (Corresponding Author) and Leonardo Da Vinci (no roles)

The header looks like this:

image

As you can see, there is no "Will Rynearson" because the contact is marked as a Document Reviewer. I'm not sure if this is correct but it makes it consistent with the code for the document view and PDF view. cc @bwbaker1

**Review by wrynearson — APPROVED** [review]
Thanks @kamicut, LGTM. Let's wait for @bwbaker1's confirmation before merging this, but it makes sense logically.

**Comment by bwbaker1** [comment]
@wrynearson @kamicut I don't think this is working correctly. In this example, I added Brad Baker (Writing role), Will Rynearson (Corresponding author), and John Doe (Document Reviewer). All three show up as authors, where John Doe should't. 

Screen Shot 2023-10-16 at 8 42 12 AM


Screen Shot 2023-10-16 at 8 43 21 AM

**Comment by wrynearson** [comment]
@bwbaker1 we haven't merged this yet, so it's not on staging yet. It will be in ~15 min

**Pull request merged**
