### PR TITLE
Move Journal Details section above Contacts section

### PR DESCRIPTION
**Pull request by frozenhelium**
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/682#issuecomment-1614721128

### CODE REVIEW

**Review by wrynearson — CHANGES_REQUESTED** [review]
Hey @frozenhelium, the order of the PDF looks good.

When a user downloads a document that doesn't have `journal details` information, the label is still listed in the PDF, and has four `No content available.` placeholders.

image

If content is added, the correct single field `Significance Discussion` is displayed.

image

If other `Journal Details` are added but _not_ `Significance Discussion`, that is also displayed correctly.

image

Could you fix the first scenario? Ideal, the entire section would not appear, but having only one `No content available.` placeholder is also a good option.

**Comment by frozenhelium** [comment]
@wrynearson I'll look into it

**Comment by frozenhelium** [comment]
@wrynearson It should be fixed now

**Review by wrynearson — CHANGES_REQUESTED** [review]
Hi @frozenhelium, there's still the issue of four "No content available." placeholders when a user selects that the ATBD will or has been published, but they don't have any content in the four field.

When a user has content in one of the four, there are then three "No content available." placeholders.

image

image

I tested this with the /pdf-preview, and it occurs there.

**Review by wrynearson — APPROVED** [review]
LGTM, thanks @frozenhelium!

**Comment by wrynearson** [comment]
Oops, forgot to merge this... doing it now @frozenhelium

**Pull request merged**
