### PR TITLE
⚠️ DON'T MERGE ⚠️ Add Playwright

### PR DESCRIPTION
**Pull request by kamicut**
Playwright is a test runner like Cypress but is faster and integrates better with our development tools.

To mark this as complete:
- [x] Base Playwright setup
- [x] Localstorage tokens
- [x] Signed In UI is as expected
- [x] Port over "create document" spec from Cypress
- [x] Replace CI and fixtures from Cypress or move to new CI fixtures

### CODE REVIEW

**Comment by kamicut** [comment]
@danielfdsilva I tagged you on this for a surface-level review (since it's a big PR) if you have the time.

Steps:
- checkout the code
- install playwright locally
- run the tests
- quick look at auth-utils.js, auth.setup.js and fixtures.js for the abstractions I used. 

Let me know if you have any questions / need more documentation.

**Comment by danielfdsilva** [comment]
@kamicut I'm not familiar with playwright to provide an in-depth review, but looking at the code I didn't see anything jumping out.
I ran this locally and 3 tests failed.

```
  1) [chromium] › contacts/edit.spec.js:23:5 › handles API error ───────────────────────────────────

    Error: response.json: Response body is unavailable for redirect responses

      12 |   await page.getByRole('button', { name: ' Save' }).click();
      13 |   page.once('response', async (response) => {
    > 14 |     const json = await response.json();
         |                                 ^
      15 |     await expect(json).url.toBe('http://example.com');
      16 |     await expect(page.getByTitle('Contact Details')).toContainText(
      17 |       'http://example.com'

        at Page.<anonymous> (/Users/daniel/guts/projects/nasa-apt-frontend/tests/contacts/edit.spec.js:14:33)

  2) [firefox] › contacts/edit.spec.js:23:5 › handles API error ────────────────────────────────────

    Error: expect: Property 'url' not found.

      13 |   page.once('response', async (response) => {
      14 |     const json = await response.json();
    > 15 |     await expect(json).url.toBe('http://example.com');
         |                       ^
      16 |     await expect(page.getByTitle('Contact Details')).toContainText(
      17 |       'http://example.com'
      18 |     );

        at Page.<anonymous> (/Users/daniel/guts/projects/nasa-apt-frontend/tests/contacts/edit.spec.js:15:23)

  3) [webkit] › contacts/edit.spec.js:23:5 › handles API error ─────────────────────────────────────

    Error: expect: Property 'url' not found.

      13 |   page.once('response', async (response) => {
      14 |     const json = await response.json();
    > 15 |     await expect(json).url.toBe('http://example.com');
         |                       ^
      16 |     await expect(page.getByTitle('Contact Details')).toContainText(
      17 |       'http://example.com'
      18 |     );

        at Page.<anonymous> (/Users/daniel/guts/projects/nasa-apt-frontend/tests/contacts/edit.spec.js:15:23)

  3 failed
    [chromium] › contacts/edit.spec.js:23:5 › handles API error ────────────────────────────────────
    [firefox] › contacts/edit.spec.js:23:5 › handles API error ─────────────────────────────────────
    [webkit] › contacts/edit.spec.js:23:5 › handles API error ──────────────────────────────────────
```

I pulled the changes on this branch and followed the steps. Anything I'm missing? Some config var perhaps?

**Comment by kamicut** [comment]
@danielfdsilva thanks for taking a look! Those 3 are flaky tests, there is a race condition that makes it such that the response is not captured before the test runner moves on. I can take a look at delaying those responses somehow to make sure they're captured

**Comment by wrynearson** [comment]
Hey @kamicut and @danielfdsilva, is anything else needed here (e.g., more review from @danielfdsilva or some changes or context from @kamicut)?

**Review by danielfdsilva — APPROVED** [review]
Besides the note on the flaky tests, the rest looks good! :)

**Comment by wrynearson** [comment]
@kamicut could you look at the branch conflicts? Once you feel ready, go ahead and merge this please!

**Pull request merged**
