### PR TITLE
Fix equations and images captions in document PDF preview

### PR DESCRIPTION
**Pull request by vgeorge**
This fixes a regression introduced in https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/549 (reported [here](https://github.com/NASA-IMPACT/nasa-apt/issues/681#issuecomment-1753109122)) where the captions and number for images and equations disappeared in the document PDF preview. 

Please note this PR only reinstates the preexisting number in document PDF preview. The following issues are still present:

- Document preview: image and table captions positioned at the bottom
- Journal preview: images caption positioned at the bottom

I suggest we handle those separately as they look more involved.

To test, open a document in document preview mode and confirm numbers are present for images, equations, and tables. Example:

- http://localhost:9000/documents/links/v1.0/pdf-preview

cc @wrynearson @sunu @kamicut

### CODE REVIEW

**Comment by vgeorge** [comment]
I added more changes to this PR. This is now fixing numbering and caption positioning on both PDF exports in preview mode. To check, visit:

http://localhost:9000/documents/links/v1.0/pdf-preview
http://localhost:9000/documents/links/v1.0/journal-pdf-preview

While these changes work in preview mode, the PDF file exported by the API do not have numbering. I'm not sure if this will be fixed once we merge this PR. @sunu would you know about this?

An additional note on this issue, we are using an approach of editing the DOM outside React using query selectors [here](https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/71cf6af56b66a78eb7c49eadf66515ca2395cba3/app/assets/scripts/components/documents/pdf-preview/index.js#L208-L213) which makes this page very hard debug and maintain. I left as is for now to avoid a big refactor, but in my opinion we should avoid this approach and refactor when possible.

**Comment by sunu** [comment]
> While these changes work in preview mode, the PDF file exported by the API do not have numbering. I'm not sure if this will be fixed once we merge this PR. @sunu would you know about this?

@vgeorge that's fine. When the local setup is running against the staging backend, the staging backend uses the staging frontend to generate the PDFs. That's why the generated PDF doesn't reflect the local changes. But it will work as expected when the frontend changes are deployed to staging after we merge the PR.

> An additional note on this issue, we are using an approach of editing the DOM outside React using query selectors [here](https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/71cf6af56b66a78eb7c49eadf66515ca2395cba3/app/assets/scripts/components/documents/pdf-preview/index.js#L208-L213) which makes this page very hard debug and maintain. I left as is for now to avoid a big refactor, but in my opinion we should avoid this approach and refactor when possible.

I totally agree and I think that's what we do by using the `NumberingContext` stuff for rendering journal PDF. eg: https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/57ca4dddc4edc3a5fbad68010bb5c52da27756b6/app/assets/scripts/components/documents/journal-pdf-preview/index.js#L315. It manages the numbering inside react instead of outside of it. And I think we should use the same approach for document PDF and view mode to avoid regressions like this in the future.

**Comment by wrynearson** [comment]
@vgeorge @sunu is this ready for review/merging? LMK if you need any action from me.

**Comment by vgeorge** [comment]
@wrynearson @kamicut @sunu I've added you to the document I linked in this post. If you see the correct numbering this is ready to merge in my opinion. We can look into the numbering context in separate as an enhancement.

**Comment by wrynearson** [comment]
Thanks @vgeorge. I won't get to this today. I'll review it on Monday.

**Review by wrynearson — APPROVED** [review]
Thanks @vgeorge! Sorry this took me so long to review. The only issue I found was that in the Journal PDF (http://localhost:9000/documents/links/v1.0/journal-pdf-preview), the equation numbers don't increment – they are both labeled as (1). Should we try to deploy this to see if the issue persists on staging?

**Comment by vgeorge** [comment]
I'll go ahead and merge to have the current enhancements on staging. I confirm the equation number is not working well in journal PDF and will look in separate.

**Pull request merged**
